service: serverless-typescript-template

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2
  timeout: 30
  # environment:
  #   STAGE: ${self:provider.stage}

functions:
  testHandler:
    handler: ./src/handlers/test.handler
    events:
      - httpApi:
          path: /test
          method: GET
