service: smart-city-climbing-trail

plugins:
  - serverless-esbuild
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-2

functions:
  test-handler:
    handler: ./src/handlers/test.handler
    events:
      - httpApi:
          path: /test/{age}
          method: GET
